#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Setup default values
server = data.get("server")
host = data.get("host")
ewi = data.get("enable_web_interface", False)
key = data.get("auth_key")

# Set env vars
agent.set_env("LOGIN_SERVER", server)
agent.set_env("TS_HOSTNAME", host)
agent.set_env("ENABLE_WEB_INTERFACE", ewi)
agent.set_env("TS_AUTHKEY", key)
