#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}

# Read current configuration from the environment file
config["server"] = os.getenv("LOGIN_SERVER","")
config["host"] = os.getenv("TS_HOSTNAME","")
config["enable_web_interface"] = os.getenv("ENABLE_WEB_INTERFACE") == "True"
config["auth_key"] = os.getenv("TS_AUTHKEY","")

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
